/**
 * Default keywords for Deepgram vocabulary boosting.
 * These are common VC/AI/software terms that benefit from explicit boosting
 * to improve transcription accuracy.
 */

export const DEFAULT_DEEPGRAM_KEYWORDS: string[] = [
  // VC / Investment Terms
  'Series A',
  'Series B',
  'Series C',
  'Series D',
  'seed round',
  'pre-seed',
  'term sheet',
  'cap table',
  'SAFE note',
  'convertible note',
  'pro rata',
  'dilution',
  'valuation',
  'ARR',
  'MRR',
  'runway',
  'burn rate',
  'due diligence',
  'LP',
  'GP',
  'portfolio company',
  'deal flow',
  'dry powder',
  'markup',
  'down round',
  'unicorn',
  'decacorn',

  // AI / ML Terms
  'LLM',
  'GPT',
  'Claude',
  'Anthropic',
  'OpenAI',
  'transformer',
  'embeddings',
  'RAG',
  'fine-tuning',
  'fine-tune',
  'inference',
  'hallucination',
  'prompt engineering',
  'context window',
  'tokens',
  'tokenization',
  'RLHF',
  'multimodal',
  'diffusion model',
  'Stable Diffusion',
  'Midjourney',
  'DALL-E',
  'vector database',
  'Pinecone',
  'Weaviate',
  'ChromaDB',
  'LangChain',
  'LlamaIndex',
  'agentic',
  'AI agent',
  'copilot',

  // Software / Tech Terms
  'API',
  'SDK',
  'SaaS',
  'PaaS',
  'IaaS',
  'microservices',
  'Kubernetes',
  'Docker',
  'CI/CD',
  'DevOps',
  'MLOps',
  'AWS',
  'Azure',
  'GCP',
  'Vercel',
  'Supabase',
  'PostgreSQL',
  'MongoDB',
  'Redis',
  'GraphQL',
  'REST API',
  'WebSocket',
  'OAuth',
  'SSO',
  'RBAC',
  'latency',
  'throughput',
  'scalability',
  'horizontally scale',
  'vertically scale',
  'load balancer',
  'CDN',
  'edge computing',
  'serverless',
  'Lambda',

  // Product / Metrics Terms
  'DAU',
  'MAU',
  'WAU',
  'NPS',
  'churn',
  'retention',
  'cohort',
  'A/B test',
  'PMF',
  'MVP',
  'GTM',
  'PLG',
  'freemium',
  'paywall',
  'onboarding',
  'activation',
  'CAC',
  'LTV',
  'ARPU',

  // Company Names (commonly discussed in VC)
  'Y Combinator',
  'YC',
  'Sequoia',
  'Andreessen Horowitz',
  'a16z',
  'Benchmark',
  'Accel',
  'Lightspeed',
  'Index Ventures',
  'Greylock',
  'Kleiner Perkins',
  'Bessemer',
  'General Catalyst',
  'Founders Fund',
  'Tiger Global',
  'SoftBank',
  'Stripe',
  'Plaid',
  'Twilio',
  'Snowflake',
  'Databricks',
  'Figma',
  'Notion',
  'Airtable',
  'Slack',
  'Discord',
  'Linear',
  'Retool',
  'Zapier',

  // Meeting / Communication
  'async',
  'standup',
  'sprint',
  'retrospective',
  'OKR',
  'KPI',
  'roadmap',
  'backlog',
  'deliverable',
  'stakeholder',
  'blockers'
]
